### ISSUE TITLE
When You Regenerate A World Trees Disappear From Forests

### ISSUE THREAD

**Issue by tristangammage** [gammagec/pixel_pioneer#45]
If You Regenerate a world Trees will suddenly disappear from any biome

**Comment by gammagec** [comment]
Ohh! this must've happened after I added the "Growing Stage".   It's the first step towards having tress & plants grow as the game goes on.  I will fix this!   But my next big change will be day & night cycles

**Comment by tristangammage** [comment]
Ok Great to know

**Comment by tristangammage** [comment]
luckily this bug was fixed or else we would had lost our trees permently
