### ISSUE TITLE
When Your Health Is Full And You Eat The Food Is Eaten Anyway

### ISSUE THREAD

**Issue by tristangammage** [gammagec/pixel_pioneer#47]
If you get food and eat when your health is full your food will be eaten anyway

**Comment by gammagec** [comment]
Now you can only eat food when you are hungry.

**Comment by gammagec** [comment]
We will have to think of another way to regen health when food is full.

**Comment by gammagec** [comment]
Maybe if standing near a fire & full, health will go up?
