### ISSUE TITLE
If you kill a mob it wont drop food every single time

### ISSUE THREAD

**Issue by tristangammage** [gammagec/pixel_pioneer#53]
if you killing a animal and killed it you get no food

**Comment by gammagec** [comment]
This was supposed to be a feature.. I didn't want every time to have a drop.

If you want to increase drop rates, look at 
world/entities/Mobs.java

For each mob, you can modify

for example
for chicken it has

// Drops
        put(null, 50);
        put(GameObjects.RAW_CHICKEN.getDefaultInstance(), 25);
        put(GameObjects.FEATHER.getDefaultInstance(), 25);
        
it means it's 50% nothing
25% chicken
25% feather

**Comment by tristangammage** [comment]
alright this feature wont be worked on
